/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Servis holati
         * @description Server tirikligini tekshiradi. Hech qanday autentifikatsiya talab qilinmaydi.
         *     Javobda: `status`, `service`, `version`, `startedAt`, `uptimeSec`, `docs`.
         *
         *     ```bash
         *     curl "$BASE_URL/health"
         *     ```
         *
         */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tayyorlik (readiness)
         * @description `READINESS_CHECK_DB=true` (productionda default) bo'lsa Postgres `SELECT 1`
         *     bilan tekshiriladi; muvaffaqiyatsiz bo'lsa **503**.
         *
         *     `READINESS_CHECK_DB=false` bo'lsa faqat jarayon tayyorligi qaytariladi (`database: skipped`).
         *
         */
        get: operations["healthReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ro'yxatdan o'tish
         * @description Yangi foydalanuvchi yaratadi va darhol `accessToken` + `refreshToken` qaytaradi.
         *
         *     - `email` lowercased va trim qilinadi (ichkarida).
         *     - `password` 8..128 belgi.
         *     - Email band bo'lsa `409 EMAIL_EXISTS`.
         *
         *     ```bash
         *     curl -X POST "$BASE_URL/auth/register" \
         *       -H "Content-Type: application/json" \
         *       -d '{"email":"vet@example.com","password":"StrongP@ss1","name":"Akmal"}'
         *     ```
         *
         */
        post: operations["authRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tizimga kirish
         * @description Mavjud foydalanuvchi bilan tizimga kiradi. `email`/`password` noto'g'ri
         *     bo'lsa, ikki holat ham bitta xato kodini qaytaradi: `401 INVALID_CREDENTIALS`
         *     (foydalanuvchi enumeratsiyasiga yo'l qo'ymaslik uchun).
         *
         *     ```bash
         *     curl -X POST "$BASE_URL/auth/login" \
         *       -H "Content-Type: application/json" \
         *       -d '{"email":"vet@example.com","password":"StrongP@ss1"}'
         *     ```
         *
         */
        post: operations["authLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Access tokenni yangilash (rotation + reuse-detection)
         * @description Access token muddati tugaganda yangi `access` + `refresh` juftligini oladi.
         *
         *     - Eski `refreshToken` avtomatik bekor qilinadi (rotation).
         *     - Allaqachon bekor qilingan token qayta yuborilsa — barcha sessiyalar
         *       bekor qilinadi va `401 REFRESH_REUSED` qaytadi.
         *     - Muddati tugagan token: `401 REFRESH_EXPIRED`.
         *
         *     ```bash
         *     curl -X POST "$BASE_URL/auth/refresh" \
         *       -H "Content-Type: application/json" \
         *       -d '{"refreshToken":"YOUR_REFRESH_TOKEN"}'
         *     ```
         *
         */
        post: operations["authRefresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh sessiyasini bekor qilish
         * @description Best-effort logout: `refreshToken` yuborilsa, mos refresh sessiyasi bekor
         *     qilinadi. Body bo'sh bo'lsa ham `200 { ok: true }` qaytadi (token mavjudligini
         *     probing qilishga yo'l qo'ymaslik uchun).
         *
         *     ```bash
         *     curl -X POST "$BASE_URL/auth/logout" \
         *       -H "Content-Type: application/json" \
         *       -d '{"refreshToken":"YOUR_REFRESH_TOKEN"}'
         *     ```
         *
         */
        post: operations["authLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clinics/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Radius bo'yicha yaqin klinikalar
         * @description **Koordinata rejimi:** `lat` va `lng` atrofidagi klinikalarni masofa bo'yicha
         *     tartiblab qaytaradi.
         *
         *     **Manzil rejimi:** faqat `address` (kamida 3 belgi) yuboring — server manzilni
         *     geokodlab, shu nuqta atrofida qidiradi. Javobda `searchCenter` (xarita markazi)
         *     keladi. `lat`/`lng` bilan `address` bir vaqtda yuborilmasligi kerak.
         *
         *     Geokodlash: OpenStreetMap Nominatim (serverda `GEOCODE_USER_AGENT` tavsiya etiladi).
         *     Manzil rejimida **geokod rate limit** (`GEOCODE_RATE_LIMIT_*`) qo'llanadi.
         *
         *     ```bash
         *     curl "$BASE_URL/clinics/nearby?lat=41.31&lng=69.25&radiusKm=5"
         *     curl "$BASE_URL/clinics/nearby?address=Toshkent%20Chilonzor&radiusKm=50"
         *     ```
         *
         */
        get: operations["clinicsNearby"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clinics/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Klinika tafsilotlari
         * @description Bitta klinikaning to'liq ma'lumotini (manzil, telefon, ish vaqti, oxirgi
         *     50 sharh) qaytaradi. Sharhlardagi `user.email` xavfsizlik uchun maskalanadi
         *     (masalan, `va***@example.com`).
         *
         *     **HTTP cache:** javobda `ETag` (zaif) va `Cache-Control: private, no-cache` beriladi.
         *     `If-None-Match` bilan oldingi `ETag` yuborilsa va o'zgarish bo'lmasa **304** qaytadi.
         *
         *     ```bash
         *     curl "$BASE_URL/clinics/CLINIC_ID"
         *     ```
         *
         */
        get: operations["clinicById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clinics/{id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sharh qoldirish (yoki mavjudini yangilash)
         * @description Har bir foydalanuvchi bitta klinikaga **bitta** sharh qoldira oladi.
         *     Qaytadan yuborilsa, oldingi sharh `rating` va `comment` qiymatlariga
         *     yangilanadi (upsert).
         *
         *     ```bash
         *     curl -X POST "$BASE_URL/clinics/CLINIC_ID/reviews" \
         *       -H "Authorization: Bearer YOUR_ACCESS_TOKEN" \
         *       -H "Content-Type: application/json" \
         *       -d '{"rating":5,"comment":"Juda yaxshi xizmat"}'
         *     ```
         *
         */
        post: operations["clinicCreateReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Boshqaruv statistikasi
         * @description Faqat `ADMIN` uchun: `users`, `clinics`, `reviews` sonlari va oxirgi 5 sharh.
         *
         *     ```bash
         *     curl "$BASE_URL/admin/dashboard" \
         *       -H "Authorization: Bearer YOUR_ADMIN_ACCESS_TOKEN"
         *     ```
         *
         */
        get: operations["adminDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/clinics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Klinikalar ro'yxati (sahifalashtirilgan)
         * @description `page`, `pageSize` va ixtiyoriy `q` (erkin matnli qidiruv —
         *     `name`, `city`, `address` bo'yicha) bilan filterlanadi.
         *
         */
        get: operations["adminListClinics"];
        put?: never;
        /**
         * Yangi klinika yaratish
         * @description Kerakli maydonlar: `name`, `phone`, `address`, `city`, `latitude`,
         *     `longitude`, `openingHours`. `openingHours` to'liq 7 kun bo'lishi shart
         *     (yopiq kun — `null`).
         *
         *     ```bash
         *     curl -X POST "$BASE_URL/admin/clinics" \
         *       -H "Authorization: Bearer YOUR_ADMIN_ACCESS_TOKEN" \
         *       -H "Content-Type: application/json" \
         *       -d '{
         *             "name":"Vet Service",
         *             "phone":"+998901234567",
         *             "address":"Chilonzor",
         *             "city":"Toshkent",
         *             "latitude":41.285,
         *             "longitude":69.204,
         *             "openingHours":{
         *               "mon":{"open":"09:00","close":"19:00"},
         *               "tue":{"open":"09:00","close":"19:00"},
         *               "wed":{"open":"09:00","close":"19:00"},
         *               "thu":{"open":"09:00","close":"19:00"},
         *               "fri":{"open":"09:00","close":"19:00"},
         *               "sat":{"open":"10:00","close":"15:00"},
         *               "sun":null
         *             }
         *           }'
         *     ```
         *
         */
        post: operations["adminCreateClinic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/clinics/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Klinika ma'lumoti (admin ko'rinish)
         * @description ID bo'yicha bitta klinika.
         */
        get: operations["adminGetClinic"];
        put?: never;
        post?: never;
        /**
         * Klinikani o'chirish
         * @description Klinikani va unga tegishli sharhlarni (cascade) o'chiradi.
         *
         *     ```bash
         *     curl -X DELETE "$BASE_URL/admin/clinics/CLINIC_ID" \
         *       -H "Authorization: Bearer YOUR_ADMIN_ACCESS_TOKEN"
         *     ```
         *
         */
        delete: operations["adminDeleteClinic"];
        options?: never;
        head?: never;
        /**
         * Klinikani yangilash
         * @description Faqat o'zgartirmoqchi bo'lgan maydonlarni yuboring. `openingHours` mavjud
         *     bo'lsa — to'liq qayta yoziladi (kun-kun merge qilinmaydi).
         *
         *     ```bash
         *     curl -X PATCH "$BASE_URL/admin/clinics/CLINIC_ID" \
         *       -H "Authorization: Bearer YOUR_ADMIN_ACCESS_TOKEN" \
         *       -H "Content-Type: application/json" \
         *       -d '{"phone":"+998901112233"}'
         *     ```
         *
         */
        patch: operations["adminUpdateClinic"];
        trace?: never;
    };
    "/admin/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sharhlar ro'yxati
         * @description `q` qidiruvi `comment`, `clinic.name`, `user.email` bo'yicha ishlaydi.
         *
         */
        get: operations["adminListReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/reviews/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Sharhni o'chirish
         * @description Moderatsiya — admin bitta sharhni o'chirib tashlaydi. Foydalanuvchi
         *     o'zining sharhini o'chira olmaydi (siyosat).
         *
         */
        delete: operations["adminDeleteReview"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Foydalanuvchilar ro'yxati
         * @description `q` qidiruvi `email`, `name` bo'yicha ishlaydi.
         *
         */
        get: operations["adminListUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Foydalanuvchi rolini o'zgartirish
         * @description `USER` <-> `ADMIN` o'zaro almashtirish. Self-protection:
         *
         *     - O'zingizdan `ADMIN` rolini olib tashlay olmaysiz -> `400 CANNOT_DEMOTE_SELF`.
         *
         *     ```bash
         *     curl -X PATCH "$BASE_URL/admin/users/USER_ID/role" \
         *       -H "Authorization: Bearer YOUR_ADMIN_ACCESS_TOKEN" \
         *       -H "Content-Type: application/json" \
         *       -d '{"role":"ADMIN"}'
         *     ```
         *
         */
        patch: operations["adminUpdateUserRole"];
        trace?: never;
    };
    "/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Foydalanuvchini o'chirish
         * @description Foydalanuvchi va uning sharhlari/refresh tokenlari cascade tarzida
         *     o'chiriladi. Self-protection: o'zingizni o'chira olmaysiz ->
         *     `400 CANNOT_DELETE_SELF`.
         *
         */
        delete: operations["adminDeleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Meta: {
            /**
             * @description So'rov bilan bog'liq UUID v4. Loglarda ham shu ID ishlatiladi.
             * @example 5d2c8b80-2e6a-4b1f-91f0-7c2c6b4f1abc
             */
            requestId?: string | null;
        };
        ErrorResponse: {
            /**
             * @example false
             * @enum {boolean}
             */
            success: false;
            error: {
                /**
                 * @description Mashinaga o'qiladigan xato kodi. Mumkin bo'lgan qiymatlar:
                 *
                 *     - **Validatsiya/so'rov:** `VALIDATION_ERROR`, `INVALID_JSON`, `PAYLOAD_TOO_LARGE`, `BAD_REQUEST`
                 *     - **Auth:** `UNAUTHORIZED`, `INVALID_TOKEN`, `TOKEN_EXPIRED`, `INVALID_CREDENTIALS`,
                 *       `INVALID_REFRESH`, `REFRESH_REUSED`, `REFRESH_EXPIRED`, `FORBIDDEN`
                 *     - **Self-protection:** `CANNOT_DEMOTE_SELF`, `CANNOT_DELETE_SELF`
                 *     - **Konflikt/topilmadi:** `EMAIL_EXISTS`, `CONFLICT`, `CLINIC_NOT_FOUND`,
                 *       `USER_NOT_FOUND`, `REVIEW_NOT_FOUND`, `NOT_FOUND`
                 *     - **Rate limit:** `RATE_LIMIT`, `AUTH_RATE_LIMIT`
                 *     - **Server:** `INTERNAL_ERROR`
                 *
                 * @example VALIDATION_ERROR
                 */
                code: string;
                /**
                 * @description O'qish uchun mo'ljallangan, foydalanuvchiga ko'rsatish mumkin bo'lgan xabar (Uzbek).
                 * @example Validatsiya xatosi
                 */
                message: string;
                /** @description Qo'shimcha tafsilot (masalan, Zod `fieldErrors`). */
                details?: unknown;
            };
            meta: components["schemas"]["Meta"];
        };
        HealthResponse: {
            /**
             * @example true
             * @enum {boolean}
             */
            success: true;
            data: {
                /** @example ok */
                status: string;
                /** @example vet-clinic-api */
                service: string;
                /** @example 1.0.0 */
                version: string;
                /** Format: date-time */
                startedAt: string;
                /** @example 1234 */
                uptimeSec: number;
                /**
                 * Format: uri
                 * @example http://localhost:4000/docs
                 */
                docs?: string | null;
            };
        };
        HealthReadyEnvelope: {
            /**
             * @example true
             * @enum {boolean}
             */
            success: true;
            data: {
                /** @example ready */
                status: string;
                /**
                 * @description skipped = READINESS_CHECK_DB=false
                 * @enum {string}
                 */
                database?: "connected" | "skipped";
                /** Format: date-time */
                timestamp: string;
            };
        };
        PublicUser: {
            /** @example clusr0001 */
            id: string;
            /**
             * Format: email
             * @example vet@example.com
             */
            email: string;
            /** @example Akmal */
            name?: string | null;
        };
        AuthPayload: {
            user: components["schemas"]["PublicUser"];
            /**
             * @description HS256 JWT, sukut bo'yicha 15 daqiqa amal qiladi.
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            accessToken: string;
            /**
             * @description 96 belgi hex string. Server tomonida SHA-256 hash bilan saqlanadi.
             * @example 3b2f5c7e9a8b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d
             */
            refreshToken: string;
        };
        AuthTokensEnvelope: {
            /**
             * @example true
             * @enum {boolean}
             */
            success: true;
            data: components["schemas"]["AuthPayload"];
        };
        RegisterRequest: {
            /**
             * Format: email
             * @example vet@example.com
             */
            email: string;
            /** @example StrongP@ss1 */
            password: string;
            /** @example Akmal */
            name?: string;
        };
        LoginRequest: {
            /**
             * Format: email
             * @example vet@example.com
             */
            email: string;
            /** @example StrongP@ss1 */
            password: string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        LogoutRequest: {
            refreshToken?: string;
        };
        OkEnvelope: {
            /**
             * @example true
             * @enum {boolean}
             */
            success: true;
            data: {
                /**
                 * @example true
                 * @enum {boolean}
                 */
                ok: true;
            };
        };
        /** @description 24-soat formatdagi ish vaqti yoki `null` (yopiq kun). */
        OpeningSlot: {
            /** @example 09:00 */
            open: string;
            /** @example 19:00 */
            close: string;
        } | null;
        /** @description Hafta kunlari bo'yicha ish vaqti (`null` — yopiq kun). Hamma 7 kun majburiy. */
        OpeningHours: {
            mon: components["schemas"]["OpeningSlot"];
            tue: components["schemas"]["OpeningSlot"];
            wed: components["schemas"]["OpeningSlot"];
            thu: components["schemas"]["OpeningSlot"];
            fri: components["schemas"]["OpeningSlot"];
            sat: components["schemas"]["OpeningSlot"];
            sun: components["schemas"]["OpeningSlot"];
        };
        ClinicSummary: {
            /** @example clu1xv8z00000abcd1234efgh */
            id?: string;
            /** @example Vet Service Chilonzor */
            name?: string;
            /** @example +998 71 123 45 67 */
            phone?: string;
            /** @example Chilonzor-9 */
            address?: string;
            /** @example Toshkent */
            city?: string;
            /**
             * Format: double
             * @example 41.285
             */
            latitude?: number;
            /**
             * Format: double
             * @example 69.204
             */
            longitude?: number;
            /**
             * Format: double
             * @example 1.27
             */
            distanceKm?: number;
            /** @example true */
            isOpenNow?: boolean;
            todayHours?: components["schemas"]["OpeningSlot"];
            /**
             * Format: double
             * @example 4.6
             */
            averageRating?: number | null;
            /** @example 12 */
            reviewCount?: number;
        };
        ClinicsNearbyEnvelope: {
            /**
             * @example true
             * @enum {boolean}
             */
            success: true;
            data: {
                clinics: components["schemas"]["ClinicSummary"][];
                /** @description Faqat `address` parametri bilan so'ralganda — xarita markazi. */
                searchCenter?: {
                    /** Format: double */
                    lat?: number;
                    /** Format: double */
                    lng?: number;
                    query?: string;
                };
            };
        };
        /** @description Klinika to'liq ma'lumoti (masofasiz). */
        ClinicDetail: {
            id?: string;
            name?: string;
            phone?: string;
            address?: string;
            city?: string;
            /** Format: double */
            latitude?: number;
            /** Format: double */
            longitude?: number;
            /**
             * Format: date-time
             * @description Oxirgi yangilanish (ETag bilan bog'langan).
             */
            updatedAt?: string;
            openingHours?: components["schemas"]["OpeningHours"];
            todayHours?: components["schemas"]["OpeningSlot"];
            isOpenNow?: boolean;
            /** Format: double */
            averageRating?: number | null;
            reviewCount?: number;
            reviews?: components["schemas"]["ReviewPublic"][];
        };
        ClinicDetailEnvelope: {
            /**
             * @example true
             * @enum {boolean}
             */
            success: true;
            data: components["schemas"]["ClinicDetail"];
        };
        ReviewPublic: {
            id?: string;
            /** @example 5 */
            rating?: number;
            /** @example Juda yaxshi xizmat */
            comment?: string | null;
            /** Format: date-time */
            createdAt?: string;
            user?: {
                id?: string;
                name?: string | null;
                /**
                 * @description Maskalangan email (masalan, `va***@example.com`).
                 * @example va***@example.com
                 */
                email?: string;
            };
        };
        ReviewCreateRequest: {
            /** @example 5 */
            rating: number;
            /** @example Tez va sifatli xizmat */
            comment?: string;
        };
        ReviewEnvelope: {
            /**
             * @example true
             * @enum {boolean}
             */
            success: true;
            data: components["schemas"]["ReviewPublic"];
        };
        Pagination: {
            /** @example 42 */
            total: number;
            /** @example 1 */
            page: number;
            /** @example 20 */
            pageSize: number;
        };
        AdminClinic: {
            id?: string;
            name?: string;
            phone?: string;
            address?: string;
            city?: string;
            /** Format: double */
            latitude?: number;
            /** Format: double */
            longitude?: number;
            openingHours?: components["schemas"]["OpeningHours"];
            reviewCount?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        AdminClinicEnvelope: {
            /**
             * @example true
             * @enum {boolean}
             */
            success: true;
            data: components["schemas"]["AdminClinic"];
        };
        AdminClinicsListEnvelope: {
            /**
             * @example true
             * @enum {boolean}
             */
            success: true;
            data: components["schemas"]["Pagination"] & {
                items: components["schemas"]["AdminClinic"][];
            };
        };
        AdminClinicCreateRequest: {
            /** @example Vet Service Chilonzor */
            name: string;
            /** @example +998 71 123 45 67 */
            phone: string;
            /** @example Chilonzor-9 */
            address: string;
            /** @example Toshkent */
            city: string;
            /**
             * Format: double
             * @example 41.285
             */
            latitude: number;
            /**
             * Format: double
             * @example 69.204
             */
            longitude: number;
            openingHours: components["schemas"]["OpeningHours"];
        };
        /** @description Faqat o'zgartirmoqchi bo'lgan maydonlarni yuboring (hammasi ixtiyoriy).
         *     Bo'sh body taqiqlanadi — kamida bitta maydon kerak.
         *      */
        AdminClinicUpdateRequest: {
            name?: string;
            phone?: string;
            address?: string;
            city?: string;
            /** Format: double */
            latitude?: number;
            /** Format: double */
            longitude?: number;
            openingHours?: components["schemas"]["OpeningHours"];
        };
        AdminUser: {
            id?: string;
            /** Format: email */
            email?: string;
            name?: string | null;
            /** @enum {string} */
            role?: "USER" | "ADMIN";
            reviewCount?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        AdminUserEnvelope: {
            /**
             * @example true
             * @enum {boolean}
             */
            success: true;
            data: components["schemas"]["AdminUser"];
        };
        AdminUsersListEnvelope: {
            /**
             * @example true
             * @enum {boolean}
             */
            success: true;
            data: components["schemas"]["Pagination"] & {
                items: components["schemas"]["AdminUser"][];
            };
        };
        AdminUserRoleUpdateRequest: {
            /**
             * @description Yangi rol. `USER` <-> `ADMIN` o'zaro almashtirish.
             *     O'zingizdan `ADMIN`ni olib tashlay olmaysiz (`CANNOT_DEMOTE_SELF`).
             *
             * @example ADMIN
             * @enum {string}
             */
            role: "USER" | "ADMIN";
        };
        AdminReview: {
            id?: string;
            rating?: number;
            comment?: string | null;
            /** Format: date-time */
            createdAt?: string;
            clinic?: {
                id?: string;
                name?: string;
            } | null;
            user?: {
                id?: string;
                /** Format: email */
                email?: string;
                name?: string | null;
            } | null;
        };
        AdminReviewsListEnvelope: {
            /**
             * @example true
             * @enum {boolean}
             */
            success: true;
            data: components["schemas"]["Pagination"] & {
                items: components["schemas"]["AdminReview"][];
            };
        };
        AdminDashboardEnvelope: {
            /**
             * @example true
             * @enum {boolean}
             */
            success: true;
            data: {
                counts: {
                    users: number;
                    clinics: number;
                    reviews: number;
                };
                latestReviews: components["schemas"]["AdminReview"][];
            };
        };
    };
    responses: {
        /** @description Validatsiya yoki noto'g'ri so'rov. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Token yo'q, yaroqsiz yoki muddati tugagan. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Ruxsat yo'q (rol yetarli emas). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resurs topilmadi. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Konflikt (masalan, email band). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description So'rov tanasi limitidan oshib ketdi (1 MB). */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Rate limit oshib ketdi. */
        TooManyRequests: {
            headers: {
                /** @description Oynadagi maksimal so'rovlar soni. */
                "RateLimit-Limit"?: number;
                /** @description Joriy oynada qolgan so'rovlar soni. */
                "RateLimit-Remaining"?: number;
                /** @description Oynaning tugashigacha qolgan soniya. */
                "RateLimit-Reset"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /**
         * @description Resurs ID (cuid).
         * @example clu1xv8z00000abcd1234efgh
         */
        IdParam: string;
        /**
         * @description Sahifa raqami (1 dan boshlanadi).
         * @example 1
         */
        Page: number;
        /**
         * @description Sahifa hajmi (1..100).
         * @example 20
         */
        PageSize: number;
        /**
         * @description Erkin matnli qidiruv (1..120 belgi).
         * @example chilonzor
         */
        Search: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Servis ishlamoqda. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    healthReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tayyor. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReadyEnvelope"];
                };
            };
            /** @description Postgres ulanmagan (faqat qat'iy readiness rejimida). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    authRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Foydalanuvchi yaratildi. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokensEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    authLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Kirish muvaffaqiyatli. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokensEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            413: components["responses"]["PayloadTooLarge"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    authRefresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Yangi access + refresh juftligi. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokensEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Token yaroqsiz, muddati tugagan yoki reuse-detection ishladi. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    authLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Har doim 200 (token bo'lmasa ham). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkEnvelope"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    clinicsNearby: {
        parameters: {
            query?: {
                /**
                 * @description Kenglik (-90..90). `address` ishlatilmasa `lng` bilan majburiy.
                 * @example 41.31
                 */
                lat?: number;
                /**
                 * @description Uzunlik (-180..180). `address` ishlatilmasa `lat` bilan majburiy.
                 * @example 69.25
                 */
                lng?: number;
                /**
                 * @description Matn manzil (kamida 3 belgi). Ko'rsatilsa `lat`/`lng` yuborilmaydi.
                 * @example Toshkent Chilonzor
                 */
                address?: string;
                /**
                 * @description Radius (km), default 10, maksimum 200.
                 * @example 5
                 */
                radiusKm?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Klinikalar (masofa bo'yicha o'sib boruvchi). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClinicsNearbyEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Manzil rejimida geokod topilmasa (`ADDRESS_NOT_FOUND`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    clinicById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Resurs ID (cuid).
                 * @example clu1xv8z00000abcd1234efgh
                 */
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Klinika va sharhlar (oxirgi 50 ta). */
            200: {
                headers: {
                    /** @description Zaif ETag — `updatedAt` bilan bog'langan. */
                    ETag?: string;
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClinicDetailEnvelope"];
                };
            };
            /** @description If-None-Match joriy ETag bilan mos — tana bo'sh. */
            304: {
                headers: {
                    ETag?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    clinicCreateReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Resurs ID (cuid).
                 * @example clu1xv8z00000abcd1234efgh
                 */
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewCreateRequest"];
            };
        };
        responses: {
            /** @description Sharh yaratildi yoki yangilandi. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            413: components["responses"]["PayloadTooLarge"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    adminDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Statistika va oxirgi sharhlar. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDashboardEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    adminListClinics: {
        parameters: {
            query?: {
                /**
                 * @description Sahifa raqami (1 dan boshlanadi).
                 * @example 1
                 */
                page?: components["parameters"]["Page"];
                /**
                 * @description Sahifa hajmi (1..100).
                 * @example 20
                 */
                pageSize?: components["parameters"]["PageSize"];
                /**
                 * @description Erkin matnli qidiruv (1..120 belgi).
                 * @example chilonzor
                 */
                q?: components["parameters"]["Search"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sahifalashtirilgan ro'yxat. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminClinicsListEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    adminCreateClinic: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminClinicCreateRequest"];
            };
        };
        responses: {
            /** @description Klinika yaratildi. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminClinicEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["PayloadTooLarge"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    adminGetClinic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Resurs ID (cuid).
                 * @example clu1xv8z00000abcd1234efgh
                 */
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Klinika ma'lumoti. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminClinicEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    adminDeleteClinic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Resurs ID (cuid).
                 * @example clu1xv8z00000abcd1234efgh
                 */
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description O'chirildi. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    adminUpdateClinic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Resurs ID (cuid).
                 * @example clu1xv8z00000abcd1234efgh
                 */
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminClinicUpdateRequest"];
            };
        };
        responses: {
            /** @description Yangilangan klinika. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminClinicEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            413: components["responses"]["PayloadTooLarge"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    adminListReviews: {
        parameters: {
            query?: {
                /**
                 * @description Sahifa raqami (1 dan boshlanadi).
                 * @example 1
                 */
                page?: components["parameters"]["Page"];
                /**
                 * @description Sahifa hajmi (1..100).
                 * @example 20
                 */
                pageSize?: components["parameters"]["PageSize"];
                /**
                 * @description Erkin matnli qidiruv (1..120 belgi).
                 * @example chilonzor
                 */
                q?: components["parameters"]["Search"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sahifalashtirilgan ro'yxat. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminReviewsListEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    adminDeleteReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Resurs ID (cuid).
                 * @example clu1xv8z00000abcd1234efgh
                 */
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description O'chirildi. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    adminListUsers: {
        parameters: {
            query?: {
                /**
                 * @description Sahifa raqami (1 dan boshlanadi).
                 * @example 1
                 */
                page?: components["parameters"]["Page"];
                /**
                 * @description Sahifa hajmi (1..100).
                 * @example 20
                 */
                pageSize?: components["parameters"]["PageSize"];
                /**
                 * @description Erkin matnli qidiruv (1..120 belgi).
                 * @example chilonzor
                 */
                q?: components["parameters"]["Search"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sahifalashtirilgan ro'yxat. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUsersListEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    adminUpdateUserRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Resurs ID (cuid).
                 * @example clu1xv8z00000abcd1234efgh
                 */
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUserRoleUpdateRequest"];
            };
        };
        responses: {
            /** @description Yangilangan foydalanuvchi. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserEnvelope"];
                };
            };
            /** @description Validatsiya yoki self-protection xatosi. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    adminDeleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Resurs ID (cuid).
                 * @example clu1xv8z00000abcd1234efgh
                 */
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description O'chirildi. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkEnvelope"];
                };
            };
            /** @description Self-protection xatosi. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
}
